services:
  - type: web
    name: random-video-chat-backend
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 10000
    plan: free